"""empty message

Revision ID: 19336b62adb3
Revises: 2a008c5aa1a3
Create Date: 2018-05-19 16:36:39.628392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19336b62adb3'
down_revision = '2a008c5aa1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('api_gene', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'api_gene')
    # ### end Alembic commands ###
