"""add file_pos in Tables

Revision ID: 26b27c9afbf9
Revises: 0c2aa98b2fb5
Create Date: 2018-07-24 01:01:08.194119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b27c9afbf9'
down_revision = '0c2aa98b2fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('file_pos', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'file_pos')
    # ### end Alembic commands ###
