"""add publickey

Revision ID: 50edd2518105
Revises: b6ea127dc51a
Create Date: 2018-04-14 12:37:43.063505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50edd2518105'
down_revision = 'b6ea127dc51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_reg', sa.Column('public_key', sa.String(length=256), nullable=True))
    op.drop_column('module_reg', 'hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_reg', sa.Column('hash', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('module_reg', 'public_key')
    # ### end Alembic commands ###
