"""add conf

Revision ID: 99f96adca0b0
Revises: dd3307ecd739
Create Date: 2018-04-14 21:55:06.082337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f96adca0b0'
down_revision = 'dd3307ecd739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_status',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('roles',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('sensitivity',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensitivity')
    op.drop_table('roles')
    op.drop_table('module_status')
    # ### end Alembic commands ###
