"""adjust fields tables

Revision ID: 9f6b19e8f385
Revises: 9b12cf603be5
Create Date: 2018-04-26 22:03:42.681356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6b19e8f385'
down_revision = '9b12cf603be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('tables', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'status')
    op.drop_column('fields', 'name')
    # ### end Alembic commands ###
