"""create tables

Revision ID: d6bea58776ba
Revises: 
Create Date: 2018-04-14 11:53:59.521360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bea58776ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_reg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.Column('certification', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('register_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('star_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('stop_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('param_description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('sensitivity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('pos', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('params', sa.String(length=256), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['sys_api.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['module_reg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('level', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module_reg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_log')
    op.drop_table('api_log')
    op.drop_table('test')
    op.drop_table('sys_log')
    op.drop_table('sys_api')
    op.drop_table('module_reg')
    # ### end Alembic commands ###
