"""add auth

Revision ID: dd3307ecd739
Revises: 50edd2518105
Create Date: 2018-04-14 21:24:31.762073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd3307ecd739'
down_revision = '50edd2518105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_reg', sa.Column('auth', sa.String(length=64), nullable=True))
    op.add_column('module_reg', sa.Column('auth_email', sa.String(length=64), nullable=True))
    op.add_column('module_reg', sa.Column('pubkey', sa.String(length=256), nullable=True))
    op.drop_column('module_reg', 'public_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_reg', sa.Column('public_key', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('module_reg', 'pubkey')
    op.drop_column('module_reg', 'auth_email')
    op.drop_column('module_reg', 'auth')
    # ### end Alembic commands ###
